snyk/driftctl-docs

docs/limitations.mdx

For https://github.com/cloudskiff/driftctl/issues/108 and https://github.com/cloudskiff/driftctl/issues/109

Add terraform apply limitation

---

docs/usage/cmd/scan/output.mdx

Add documentation to explain computed fields

---

docusaurus.config.js
src/pages/index.js

`docs.driftctl.com/` will be redirected to `docs.driftctl.com/<latestVersion>/`

Change path for latest version and redirect to it

---

docs/usage/filtering/driftignore.mdx
docs/usage/filtering/rules.mdx
sidebars.js

Filtering has now its own path under Usage

Change filtering docs

---

docs/usage/cmd/scan/iac-source.mdx

For https://github.com/cloudskiff/driftctl/issues/286

Add unsupported backend documentation

---

docs/ci_cd/guides/circleci.mdx
docs/ci_cd/guides/ghaction.mdx
sidebars.js

For issue cloudskiff/driftctl/issues/281

Add GitHub Action docs

---

docs/usage/filtering/driftignore.mdx
versioned_docs/version-0.4.0/usage/cmd/scan/filter.mdx
versioned_docs/version-0.5.0/usage/cmd/scan/filter.mdx
versioned_docs/version-0.6.0/usage/cmd/scan/filter.mdx

environement -> environment. Pretty straight forward.

Spelling mistake in Filtering page

---

docs/installation.mdx
docs/usage.mdx
sidebars.js

Add more docker usage examples

---

docs/usage/cmd/scan/iac-source.mdx

- https://github.com/cloudskiff/driftctl/pull/335

Add usage with URL

---

docs/usage/flags/version-check.mdx

Add docs about telemetry on version check

---

versioned_docs/version-0.7.1/usage/cmd/scan.mdx

Output terminology

---

docusaurus.config.js

Related to cloudskiff/driftctl-docs#36

Add deep links

---

docs/usage/flags/crash-reporting.mdx
sidebars.js
versioned_docs/version-0.7.1/usage/flags/crash-reporting.mdx
versioned_sidebars/version-0.7.1-sidebars.json

Update doc for crash reporting

---

docs/usage/cmd/scan.mdx

Terminology was not fixed for upcoming next version.
Related to #35

Fix terminology and invalid json output

---

docs/usage/cmd/scan.mdx
versioned_docs/version-0.7.1/usage/cmd/scan.mdx

Strict mode documentation

---

docs/providers/aws/authentication.mdx

A duplicate of @bertux PR for a custom read-only role written in HCL to apply with Terraform.

Terraform custom role

---

docs/usage/flags/crash-reporting.mdx
versioned_docs/version-0.8.0/usage/flags/crash-reporting.mdx

Documentation for cloudskiff/driftctl#452

Add a note about crash reporting behavior

---

docs/usage/flags/disable-telemetry.mdx
sidebars.js

Related to https://github.com/cloudskiff/driftctl/issues/441 and https://github.com/cloudskiff/driftctl/issues/442

Add telemetry doc

---

docs/limitations.mdx
versioned_docs/version-0.8.0/limitations.mdx

Add documentation for https://github.com/cloudskiff/driftctl/pull/361

Behavior with unsupported Terraform versions

---

docs/usage/filtering/driftignore.mdx
versioned_docs/version-0.8.0/usage/filtering/driftignore.mdx

Add documentation for cloudskiff/driftctl#433

Usage of gen-driftignore command

---

docs/usage.mdx
docs/usage/cmd/scan.mdx
versioned_docs/version-0.8.0/usage.mdx
versioned_docs/version-0.8.0/usage/cmd/scan.mdx

Add documentation for cloudskiff/driftctl#353

Usage with glob patterns

---

docs/usage/filtering/driftignore.mdx
versioned_docs/version-0.8.0/usage/filtering/driftignore.mdx

This reverts commit cfea94343b2b2bba6203a7321aae8c81a2fcec6e, reversing
changes made to 7b103ba0a4aff21efa1a8cf58255aa9ccae9cbce.

Remove docs about gen-driftignore command

---

docs/usage/flags/disable-telemetry.mdx
versioned_docs/version-0.8.0/usage/flags/disable-telemetry.mdx

https://docs.driftctl.com/0.8.0/usage/flags/disable-telemetry

Fix a typo in telemetry doc

---

docs/ci_cd/intro.mdx
versioned_docs/version-0.9.0/ci_cd/intro.mdx

cancerous stuff might be a little overkill in this case :) (+the word "curated" is imho incorrect)
i kept it for past doc versions

waiting for a better wording, let's remove this

---

docs/usage/cmd/scan.mdx

https://github.com/cloudskiff/driftctl/issues/555

Issue 555: Add config-dir flag doc

---

docs/providers/aws/authentication.mdx

https://github.com/cloudskiff/driftctl/pull/671
Is this the good place in the doc to add this content ?

Add a different authentication mechanism for S3 bucket

---

docs/providers/aws/resources.mdx
docs/providers/github/resources.mdx
docs/usage/cmd/scan.mdx
src/pages/deep-mode.js

For https://github.com/cloudskiff/driftctl/issues/819

Add documentation about deep mode

---

docs/usage/cmd/scan.mdx

For https://github.com/cloudskiff/driftctl/issues/874

Add doc about resource source in JSON

---

docs/usage/filtering/rules.mdx

Fix https://github.com/cloudskiff/driftctl/issues/922

Add filter and deep mode clarification

---

docs/providers/aws/authentication.mdx
docs/providers/aws/resources.mdx

Following https://github.com/cloudskiff/driftctl/pull/1010

Add docs for RDS resources

---

docs/providers/aws/authentication.mdx
docs/providers/aws/resources.mdx

Link to https://github.com/cloudskiff/driftctl/pull/1022

Add permissions and resource in the list for aws_cloudformation_stack resource

---

docs/providers/aws/authentication.mdx
docs/providers/aws/resources.mdx

With https://github.com/cloudskiff/driftctl/pull/1026

Add aws_api_gateway_rest_api resource

---

docs/usage/filtering/rules.mdx

For https://github.com/cloudskiff/driftctl-docs/issues/100

Fix filtering attribute reference doc

---

versioned_docs/version-0.15.0/usage/filtering/driftignore.mdx

@eliecharra has pointed out that this sentence from the docs was outdated and should be removed.

Update filtering docs

---

docs/providers/google/resources.mdx

docs for https://github.com/cloudskiff/driftctl/pull/1067

Add google_compute_router resource

---

docs/providers/aws/authentication.mdx
docs/providers/aws/resources.mdx

docs for https://github.com/cloudskiff/driftctl/pull/946

Add aws_appautoscaling_target resource

---

docs/providers/aws/resources.mdx

Link https://github.com/cloudskiff/driftctl/pull/1084

Add aws_api_gateway_authorizer

---

docs/usage/cmd/scan.mdx

Depends on https://github.com/cloudskiff/driftctl/pull/1216

Updated documentation for Terraform Enterprise.

---

docs/providers/aws/resources.mdx

based on https://github.com/cloudskiff/driftctl-docs/pull/182

Add aws_apigatewayv2_api resource

---

docs/usage/cmd/scan.mdx

Documentation for terraform cloud workspace name support

feat: add workspace name example

---

docs/providers/aws/resources.mdx

Reordered apigatewayv2 resources inside the list of supported resources and added the new route_response resource

Add aws_apigatewayv2_route_response resource

---

docs/providers/aws/resources.mdx

Requires https://github.com/snyk/driftctl/pull/1321, do not merge until after that.
Related: https://github.com/snyk/driftctl/issues/1310

Add aws_apigatewayv2_deployment

---

docs/ci_cd/guides/gitlabci.mdx

replace cloudskiff by cloudskiff

fix(url): change broken link

---

docs/usage/cmd/scan.mdx
versioned_docs/version-0.22.0/usage/cmd/scan.mdx

Related to https://github.com/snyk/driftctl/pull/1359.

New --only-managed / --only-unmanaged flags

---

docs/usage/cmd/scan.mdx

Related to https://github.com/snyk/driftctl/pull/1371

Add total_iac_source_count json field

---

docs/usage/cmd/scan.mdx

Related to https://github.com/snyk/driftctl/pull/1373

Add scan_duration JSON field

---

docs/providers/google/resources.mdx

Related to https://github.com/snyk/driftctl/pull/1453

feat: add google_compute_global_forwarding_rule

---

docs/providers/google/resources.mdx
versioned_docs/version-0.26.0/providers/google/resources.mdx

related to [#1379](https://github.com/snyk/driftctl/pull/1379)

Add google_compute_instance_group_manager

---

docs/usage/cmd/scan.mdx
versioned_docs/version-0.35.0/usage/cmd/scan.mdx

Add note about tfstate discovering

---

.github/CODEOWNERS

See https://github.com/snyk/driftctl/pull/1574

Fix codeowner team name
