snyk/driftctl-docs

docusaurus.config.js
package-lock.json
package.json

To fix cloudskiff/driftctl/issues/317, let's redirect /installation to /<latest>/installation

Add redirection to latest installation

---

docs/providers/aws/authentication.mdx

It misses an explanation about how to attach and use our limited role after launching the CloudFormation stack.

More information about how to use the limited role

---

docs/usage/cmd/scan.mdx

Adding an example for Gitlab Terraform state with HTTP backend, following https://github.com/cloudskiff/driftctl/issues/270.
----

Add usage example for http & gitlab

---

docs/usage/cmd/scan.mdx

While testing out this command on a private GitLab repository, I realized the example had a typo that lead the HTTP request to not send any header, resulting in the following response from GitLab : `{"message":"401 Unauthorized"}`. This could be confusing to the user.

Fix a typo in HTTP + GitLab example

---

versioned_docs/version-0.7.0/installation.mdx

-L options was omitted for windows links

add follow links to windows curl command

---

docs/usage/filtering/driftignore.mdx

Related to #43.
We should talk about .driftignore file taking precedence over filter rules.

.driftignore takes precedence over filter rules

---

docs/usage/cmd/scan.mdx
versioned_docs/version-0.8.0/usage/cmd/scan.mdx

This PR adds documentation for [Support for Terraform Cloud / Terraform Enterprise](https://github.com/cloudskiff/driftctl/pull/458).

Support for Terraform Cloud / Terraform Enterprise

---

docusaurus.config.js

related to https://github.com/cloudskiff/driftctl/issues/459
Add a missing deep link for GitHub authentication doc.

Add missing deep link for github auth doc

---

docs/usage/cmd/scan.mdx
versioned_docs/version-0.8.0/usage/cmd/scan.mdx

it was described as a main usage example but not as a detailed `--from` usage example

add glob pattern usage example

---

docs/installation.mdx
versioned_docs/version-0.8.0/installation.mdx

Default is `/root` and not `/home` from the old image. 
(we should stop using root at some point in the near future too)

use correct home folder for alpine

---

docusaurus.config.js

This will redirect our users to `Intros` channel instead of `Stargazer`

Change Discord Url

---

docs/providers/aws/authentication.mdx
versioned_docs/version-0.12.0/providers/aws/authentication.mdx
versioned_docs/version-0.13.0/providers/aws/authentication.mdx
versioned_docs/version-0.14.0/providers/aws/authentication.mdx

Fix a typo in AWS authentication

---

docs/usage/filtering/driftignore.mdx
versioned_docs/version-0.14.0/usage/filtering/driftignore.mdx

Following https://github.com/cloudskiff/driftctl-docs/pull/117, may be we should remove that sentence from current version as well

Update filtering docs

---

docs/usage/cmd/gen-driftignore.mdx

The default location to read drift input from, and write ignore rules
to, was changed in https://github.com/cloudskiff/driftctl/pull/1208.
Update usage examples as a result.
---
Am I right in thinking that changing this file will cause this doc to be entered into the next release?

Update gen-driftignore I/O flags docs

---

docs/providers/aws/resources.mdx

No new permissions needed since AWS use the same `"apigateway:GET",` action for the v2

Add aws_apigatewayv2_vpc_link resource

---

versioned_docs/version-0.17.0/providers/aws/resources.mdx

The resource is missing in v0.17.
Closes #198

Add aws_apigatewayv2_api

---

docs/providers/aws/resources.mdx

Introduced in https://github.com/snyk/driftctl/pull/1252. Don't merge this until that's accepted!

Document support for aws_apigatewayv2_route

---

.github/workflows/release.yml
package.json
scripts/auto-versioning.sh
scripts/release-latest-version.sh

Currently, the documentation of driftctl is located in another Git repo (snyk/driftctl-docs). Merging in main branch triggers a deployment of the website. Each time we release a new version of driftctl, we have to manually create a new branch with the new version, create a PR for it, wait for approval then merge and deploy it to production. That’s a really long process that doesn’t fit with our needs anymore, as we want to release more often and quicker.
It’s actually possible to trigger a GitHub action pipeline manually using the dispatch event of the GitHub API. This PR adds a release workflow to automatically create a new version based on the latest driftctl version. The script checks whether if the version already exist or if it's a patch release. This action will then be triggered by …

Create release automation workflow

---

docs/usage/cmd/scan.mdx

**Rearrange nesting in scan usage**
Nest flag docs under options, rather than have them as siblings. Move
whole options tree up one level to be a sibling of description, at the
top level of the doc. Nest all subsections of flags under flags, rather
than have them be siblings of flags.
**Document scan exit codes**
---
Documents https://github.com/snyk/driftctl/pull/1353.
Related: https://github.com/snyk/driftctl/issues/1350

Document scan exit codes

---

.snyk

This repo is being scanned by `snyk-iac-group-seceng`: https://app.snyk.io/org/snyk-iac-group-seceng/project/01868049-d1f7-48cd-ad59-d9bb10f6fe89
There quite a few vulnerabilities, some of which can be fixed by updating `@docusaurus` package from `2.0.0-beta.9` to `2.0.0-beta.17`. 
While attempting this I ran into a few problems:
- (fixed) had to update `@theme/hooks` to `@docusaurus/theme-common`
- `Error: Cannot find module 'webpack/package.json'`
- this was fixed in `react-loadable-ssr-addon@1.0.2` but `@docusaurus` use their own forked version of this library which is stuck at `/react-loadable-ssr-addon-v5-slorber@1.0.1` (https://www.npmjs.com/package/react-loadable-ssr-addon-v5-slorber)
- there is a recent issue with activity that might fix this: …

chore: ignore unfixable vulnerabilities

---

package-lock.json
package.json

```
@docusaurus/core@2.4.1 > @docusaurus/mdx-loader@2.4.1 > @mdx-js/mdx@1.6.22 > remark-mdx@1.6.22 > remark-parse@8.0.3 > trim@0.0.1
```
`trim` is fixed at `0.0.1` by  [remark-parse 8.0.3](https://www.npmjs.com/package/remark-parse/v/8.0.3?activeTab=code) Upgrading to 0.0.3 fixes the issue and unlocks allows to address other dependency vulnerabilities. 
A check of the diff between [trim 0.0.1 and 0.0.3](https://github.com/Trott/trim/compare/0.0.1...v0.0.3) shows that the functionality should not be impacted despite [this](https://github.com/remarkjs/remark/issues/710). This is confirmed by testing the documentation locally.

fix: dependency vulnerabilities

---

.circleci/config.yml
package-lock.json

This is classified as a docs repo, however it contains deps (mostly `docusaurus`) so is worth scanning.
- Add sec scans
- Fix 8xH vulns with `npm fix audit`

chore: add security scanning
